version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - /postgres/data/postgres
    ports:
      - "5432:5432"

    networks:
      - postgres-network
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
    restart: unless-stopped


networks:
  postgres-network:
    driver: bridge